### ISSUE TITLE
api no longer public?

### ISSUE THREAD

**Issue by japrescott** [BBC-News-Labs/newsQuery#12]
hello Iain
Sadly it seems the api isn't available for people outside of bbc? Do you have any information about this or how to obtain an api key (besides waiting paciently)?
Thanks for your insight
Jeremy

**Comment by iaincollins** [comment]
The API Platform team restricted sign up to BBC staff on the new API platform, which meant it wasn't possible for people to sign up any more.

We've now addressed this by embedding an API key inside the library, so the registration process is no longer nesseary (it's now works 'out of the box').

Apologies to anyone who ran into problems with not being able to register perviously!
